# Generated by Django 2.2 on 2020-01-01 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单内的商品详情',
                'verbose_name_plural': '订单内的商品详情',
                'db_table': 'order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(default='', max_length=50, unique=True, verbose_name='订单编号')),
                ('nonce_str', models.CharField(default='', max_length=50, verbose_name='随机加密串')),
                ('trade_no', models.CharField(default='', max_length=50, verbose_name='交易号')),
                ('pay_status', models.CharField(choices=[('已支付', '已支付'), ('超时关闭', '超时关闭'), ('交易创建', '交易创建'), ('交易结束', '交易结束'), ('待支付', '待支付')], default='待支付', max_length=20, verbose_name='订单状态')),
                ('pay_type', models.CharField(choices=[('已支付', '已支付'), ('超时关闭', '超时关闭'), ('交易创建', '交易创建'), ('交易结束', '交易结束'), ('待支付', '待支付')], default='支付宝', max_length=10, verbose_name='支付类型')),
                ('post_script', models.TextField(blank=True, default='', help_text='订单留言', null=True, verbose_name='订单留言')),
                ('order_mount', models.FloatField(default=0.0, help_text='订单金额', verbose_name='订单金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('address', models.CharField(default='', help_text='收货地址', max_length=100, verbose_name='收货地址')),
                ('signer_name', models.CharField(default='', help_text='签收人', max_length=20, verbose_name='签收人')),
                ('signer_mobile', models.CharField(default='', help_text='联系电话', max_length=11, verbose_name='联系电话')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='购买数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'shopping_cart',
            },
        ),
    ]
